name: array_to_excel
description: >-
  A Flutter package to generate Excel files from arrays and allow users to save or share the file on Android, iOS, Web, and Desktop.
version: 1.0.1
homepage: https://github.com/toniSed/array_to_excel.git
repository: https://github.com/toniSed/array_to_excel.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  file_picker: ^10.2.0
  share_plus: ^11.0.0

  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

# Example for pub.dev
example:
  - example/lib/main.dart
