name: arrayToExcel
description: >-
  A Flutter package to generate Excel files from arrays and allow users to save or share the file on Android, iOS, Web, and Desktop.
version: 1.0.0
homepage: https://github.com/yourusername/arrayToExcel
repository: https://github.com/yourusername/arrayToExcel

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.2 # Use a more recent version
  file_picker: ^8.0.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

# Example for pub.dev
example:
  - example/lib/main.dart
